name: Create Tile and app.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-tile:
    runs-on: codebuild-yaizu-city-opendata-${{ github.run_id }}-${{ github.run_attempt }}

    permissions:
      contents: write
      id-token: write

    steps:

      - name: Install packages
        run: |
          apt-get update && \
          apt-get install -y \
          curl \
          jq \
          tar \
          gcc \
          g++ \
          make \
          libsqlite3-dev \
          zlib1g-dev \

      - name: Install Tippicanoe
        run: |
          TIPPECANOE_VERSION=2.66.0 && \
          curl -L https://github.com/felt/tippecanoe/archive/refs/tags/${TIPPECANOE_VERSION}.tar.gz -o tippecanoe.tar.gz && \
          tar -xzvf tippecanoe.tar.gz && \
          cd tippecanoe-${TIPPECANOE_VERSION} && \
          make -j && \
          make install

      - run: |
          tippecanoe --version

      # - name: Install GDAL (for ogr2ogr)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gdal-bin

      # - run: |
      #     gdalinfo --version
      #     ogr2ogr --version
  